// frontend/src/components/header/header.tsx
import { useEffect, useState } from 'react';
import AppLogo from '../../shared/components/app-logo';
import AccountButton from './account-button/account-button';
import GlobalMarketBar from './global-market-bar/global-market-bar';
import HeaderSearchBar from './header-search-bar/header-search-bar';
import './header.scss';
import Navigation from './navigation/navigation';
import ThemeButton from './theme-button';

export default function Header() {
  const [isBigHeader, setIsBigHeader] = useState(getIsBigHeader);

  useEffect(() => {
    const changeHeader = () => setIsBigHeader(getIsBigHeader());
    window.addEventListener('resize', changeHeader);

    return () => window.removeEventListener('resize', changeHeader);
  }, []);

  function getIsBigHeader(): boolean {
    // This value must match the media qeury value in css
    return window.innerWidth >= 749;
  }

  return (
    < header >
      <div className="header-content-wrapper">
        {isBigHeader ? <BigHeader /> : <SmallHeader />}
      </div>
    </header >
  );
}

function BigHeader() {
  return (
    <>
      <div className="upper-header">
        <GlobalMarketBar />

        <div className="upper-header-right">
          <ThemeButton />
          <AccountButton />
        </div>
      </div>

      <div className="lower-header">
        <AppLogo />
        <Navigation />
        <HeaderSearchBar />
      </div>
    </>
  );
}

function SmallHeader() {
  return (
    <>
      <div className="upper-header">
        <div className='upper-header-left'>
          <Navigation />
          <AppLogo />
        </div>

        <div className="upper-header-right">
          <ThemeButton />
          <AccountButton />
        </div>
      </div>

      <div className="lower-header">
        <HeaderSearchBar />
      </div>
    </>
  );
}

// frontend/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { GlobalMarketBarComponent } from "./global-market-bar/global-market-bar.component";
import { AccountButtonComponent } from "./account-button/account-button.component";
import { NavigationComponent } from "./navigation/navigation.component";
import { HeaderSearchBarComponent } from "./header-search-bar/header-search-bar.component";
import { ThemeButtonComponent } from "./theme-button/theme-button.component";
import { AppLogoComponent } from "../../shared/components/app-logo/app-logo.component";

@Component({
  selector: 'ms-header',
  imports: [GlobalMarketBarComponent, AccountButtonComponent, NavigationComponent, HeaderSearchBarComponent, ThemeButtonComponent, AppLogoComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {

}

<div class="header-content-wrapper">
  @if (true) {
  <div class="upper-header">
    <ms-global-market-bar />

    <div class="upper-header-right">
      <ms-theme-button />
      <ms-account-button />
    </div>
  </div>

  <div class="lower-header">
    <ms-app-logo />
    <ms-navigation />
    <ms-header-search-bar />
  </div>

  } @else {
  <div class="upper-header">
    <div class='upper-header-left'>
      <ms-navigation />
      <ms-app-logo />
    </div>

    <div class="upper-header-right">
      <ms-theme-button />
      <ms-account-button />
    </div>
  </div>

  <div class="lower-header">
    <ms-header-search-bar />
  </div>
  }

</div>
