// frontend/src/components/header/theme-button.tsx
import { useEffect, useState } from "react";

export default function ThemeButton() {
  const [isDarkTheme, setIsDarkTheme] = useState(getIsDarkTheme);

  useEffect(() => toggleAppTheme(isDarkTheme), [isDarkTheme]);

  function getIsDarkTheme(): boolean {
    return JSON.parse(localStorage.getItem('isDarkTheme') || 'true');
  }

  function handleClick(): void {
    setIsDarkTheme(prev => !prev);
  }

  return (
    <button className='icon-button theme-button' onClick={handleClick}>
      {isDarkTheme
        ? <i className="bi bi-sun-fill"></i>
        : <i className="bi bi-moon-fill"></i>
      }
    </button>
  );
}

function toggleAppTheme(isDarkTheme: boolean): void {
  if (isDarkTheme)
    document.body.classList.remove('light-theme');
  else
    document.body.classList.add('light-theme');

  localStorage.setItem('isDarkTheme', JSON.stringify(isDarkTheme));
}

// frontend/src/app/components/header/theme-button/theme-button.component.ts
import { Component, effect, signal } from '@angular/core';

@Component({
  selector: 'ms-theme-button',
  imports: [],
  templateUrl: './theme-button.component.html',
  styleUrl: './theme-button.component.scss'
})
export class ThemeButtonComponent {
  isDarkTheme = signal(true);

  constructor() {
    this.setInitialTheme();
    effect(() => this.toggleAppTheme());
  }

  setInitialTheme(): void {
    const isDarkTheme = JSON.parse(localStorage.getItem('isDarkTheme') || 'true');
    this.isDarkTheme.set(isDarkTheme);
  }

  toggleColorTheme(): void {
    this.isDarkTheme.set(!this.isDarkTheme());
  }

  toggleAppTheme(): void {
    if (this.isDarkTheme())
      document.body.classList.remove('light-theme');
    else
      document.body.classList.add('light-theme');

    localStorage.setItem('isDarkTheme', JSON.stringify(this.isDarkTheme()));
  }
}

<button class='icon-button theme-button' (click)="toggleColorTheme()">
  @if (isDarkTheme()) {
  <i class="bi bi-sun-fill"></i>

  } @else {
  <i class="bi bi-moon-fill"></i>
  }
</button>
