// frontend/src/components/header/navigation/navigation.tsx
import { NavLink } from 'react-router';
import './navigation.scss';
import { useState } from 'react';

export default function Navigation() {
  const [isNavMenuOpen, setIsNavMenuOpen] = useState(false);

  function toggleNavMenu(): void {
    setIsNavMenuOpen(prevVal => !prevVal);
  }

  return (
    <>
      <button className='navigation-toggle' onClick={toggleNavMenu}>
        <i className="bi bi-list"></i>
        <i className="bi bi-x-lg"></i>
      </button>

      <nav className={`header-nav${isNavMenuOpen ? ' open' : ''}`}>
        <ul className="left-nav">
          <li>
            <NavLink to='/' >Coins</NavLink >
          </li>
          <li>
            <NavLink to='/' >Exchanges</NavLink >
          </li>
        </ul>

        <ul className="right-nav">
          <li>
            <NavLink to='/' >Watchlist</NavLink >
          </li>
          <li>
            <NavLink to='/' >Portfolio</NavLink >
          </li>
        </ul>
      </nav >
    </>
  );
}

// frontend/src/app/components/header/navigation/navigation.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'ms-navigation',
  imports: [],
  templateUrl: './navigation.component.html',
  styleUrl: './navigation.component.scss'
})
export class NavigationComponent {

}

<button class='navigation-toggle' (click)='toggleNavMenu()'>
  <i [class]='"bi bi-" + (isNavMenuOpen() ? "x-lg" : "list" )'></i>
</button>

<nav class='header-nav' [class.open]="isNavMenuOpen()">
  <ul class="left-nav">
    <li>
      <a routerLink="/">Coins</a>
    </li>
    <li>
      <a routerLink="/">Exchanges</a>
    </li>
  </ul>

  <ul class="right-nav">
    <li>
      <button class='icon-button' (click)="onIconButtonClick('watchlist')">
        <i [class]='"bi bi-star" + (router.url === "/watchlist" ? "-fill" : "" )'></i>
        <span>Watchlist</span>
      </button>
    </li>
    <li>
      <button class='icon-button' (click)="onIconButtonClick('portfolio')">
        <i [class]='"bi bi-pie-chart" + (router.url === "/portfolio" ? "-fill" : "" )'></i>
        <span>Portfolio</span>
      </button>
    </li>
  </ul>
</nav>
